---
title: "CodeBook"
author: "Patrick Hawkins"
date: "Saturday, April 25, 2015"
output: html_document
---
Variables in TidyData.Txt File

"Activity"
"Subject"
"TimeBodyAccelerationMeanXaxis"
"TimeBodyAccelerationMeanYaxis"
"TimeBodyAccelerationMeanZaxis"
"TimeBodyAccelerationStdDevXaxis"
"TimeBodyAccelerationStdDevYaxis"
"TimeBodyAccelerationStdDevZaxis"
"TimeGravityAccelerationMeanXaxis"
"TimeGravityAccelerationMeanYaxis"
"TimeGravityAccelerationMeanZaxis"
"TimeGravityAccelerationStdDevXaxis"
"TimeGravityAccelerationStdDevYaxis"
"TimeGravityAccelerationStdDevZaxis"
"TimeBodyAccelerationJerkSignalMeanXaxis"         
"TimeBodyAccelerationJerkSignalMeanYaxis"
"TimeBodyAccelerationJerkSignalMeanZaxis"
"TimeBodyAccelerationJerkSignalStdDevXaxis"       
"TimeBodyAccelerationJerkSignalStdDevYaxis"
"TimeBodyAccelerationJerkSignalStdDevZaxis"
"TimeBodyGyroscopeMeanXaxis"                      
"TimeBodyGyroscopeMeanYaxis"
"TimeBodyGyroscopeMeanZaxis"
"TimeBodyGyroscopeStdDevXaxis"                    
"TimeBodyGyroscopeStdDevYaxis"
"TimeBodyGyroscopeStdDevZaxis"
"TimeBodyGyroscopeJerkSignalMeanXaxis"            
"TimeBodyGyroscopeJerkSignalMeanYaxis"
"TimeBodyGyroscopeJerkSignalMeanZaxis"
"TimeBodyGyroscopeJerkSignalStdDevXaxis"          
"TimeBodyGyroscopeJerkSignalStdDevYaxis"
"TimeBodyGyroscopeJerkSignalStdDevZaxis"
"TimeBodyAccelerationMagnitudeMean"               
"TimeBodyAccelerationMagnitudeStdDev"
"TimeGravityAccelerationMagnitudeMean"
"TimeGravityAccelerationMagnitudeStdDev"          
"TimeBodyAccelerationJerkSignalMagnitudeMean"
"TimeBodyAccelerationJerkSignalMagnitudeStdDev"
"TimeBodyGyroscopeMagnitudeMean"                  
"TimeBodyGyroscopeMagnitudeStdDev"
"TimeBodyGyroscopeJerkSignalMagnitudeMean"
"TimeBodyGyroscopeJerkSignalMagnitudeStdDev"      
"FFTFreqBodyAccelerationMeanXaxis"
"FFTFreqBodyAccelerationMeanYaxis"
"FFTFreqBodyAccelerationMeanZaxis"                
"FFTFreqBodyAccelerationStdDevXaxis"
"FFTFreqBodyAccelerationStdDevYaxis"
"FFTFreqBodyAccelerationStdDevZaxis"              
"FFTFreqBodyAccelerationJerkSignalMeanXaxis"
"FFTFreqBodyAccelerationJerkSignalMeanYaxis"
"FFTFreqBodyAccelerationJerkSignalMeanZaxis"      
"FFTFreqBodyAccelerationJerkSignalStdDevXaxis"
"FFTFreqBodyAccelerationJerkSignalStdDevYaxis"
"FFTFreqBodyAccelerationJerkSignalStdDevZaxis"    
"FFTFreqBodyGyroscopeMeanXaxis"
"FFTFreqBodyGyroscopeMeanYaxis"
"FFTFreqBodyGyroscopeMeanZaxis"                   
"FFTFreqBodyGyroscopeStdDevXaxis"
"FFTFreqBodyGyroscopeStdDevYaxis"
"FFTFreqBodyGyroscopeStdDevZaxis"                 
"FFTFreqBodyAccelerationMagnitudeMean"
"FFTFreqBodyAccelerationMagnitudeStdDev"
"FFTFreqBodyAccelerationJerkSignalMagnitudeMean"  
"FFTFreqBodyAccelerationJerkSignalMagnitudeStdDev"
"FFTFreqBodyGyroscopeMagnitudeMean"
"FFTFreqBodyGyroscopeMagnitudeStdDev"             
"FFTFreqBodyGyroscopeJerkSignalMagnitudeMean"
"FFTFreqBodyGyroscopeJerkSignalMagnitudeStdDev"  